server:
  port: 8411
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/brankb?characterEncoding=UTF-8
    username: root
    password: root2019..

eureka:
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}


tx-lcn:
  client:
    manager-address: 127.0.0.1:8070