server:
  port: 8410
spring:
  application:
    name: branka-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/branka?characterEncoding=UTF-8
    username: root
    password: Iamapig0.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}


tx-lcn:
  client:
    manager-address: 127.0.0.1:8070